### ISSUE TITLE
"plot_list" does not exist in the java interpreter.

### ISSUE THREAD

**Issue by VergilPrime** [PseudoKnight/CHPlotSquared#1]

**Comment by PseudoKnight** [comment]
Which version are you using and on which CH build? There's nothing special about that function.

**Comment by VergilPrime** [comment]
Spigot 1.8.8, CH snapshot 3021.

**Comment by PseudoKnight** [comment]
I meant which version of CHPlotSquared. You should be using 0.1.0 on that build of CH.
